// AUTO-GENERATED by scripts/sync_frontend_content.py -- do not edit by hand.
export type SitemapLink = {
  to: string
  label: string
  asset?: boolean
}

export type SitemapSection = {
  title: string
  links: SitemapLink[]
}

export const publicSitemapSections: SitemapSection[] = [
  {
    title: "Main Pages",
    links: [
      {
        to: "/",
        label: "Home"
      },
      {
        to: "/about",
        label: "About Us"
      },
      {
        to: "/services",
        label: "Services"
      },
      {
        to: "/pricing",
        label: "Pricing"
      },
      {
        to: "/contact",
        label: "Contact"
      },
      {
        to: "/sitemap",
        label: "Sitemap"
      }
    ]
  },
  {
    title: "Services",
    links: [
      {
        to: "/services/web-design",
        label: "Web Design & Development"
      },
      {
        to: "/services/mobile-apps",
        label: "Mobile App & APK Development"
      },
      {
        to: "/services/digital-marketing",
        label: "Digital Marketing & SEO"
      },
      {
        to: "/services/ai-solutions",
        label: "AI & Machine Learning"
      },
      {
        to: "/services/software-development",
        label: "Custom Software Development"
      },
      {
        to: "/services/advertising",
        label: "Advertising & Ad Tech"
      },
      {
        to: "/services/ecommerce",
        label: "E-commerce Solutions"
      }
    ]
  },
  {
    title: "Products",
    links: [
      {
        to: "/billingflow",
        label: "BillingFlow"
      },
      {
        to: "/billingflow/features",
        label: "BillingFlow Features"
      },
      {
        to: "/billingflow/pricing",
        label: "BillingFlow Pricing"
      },
      {
        to: "/billingflow/docs",
        label: "BillingFlow Docs"
      },
      {
        to: "/billingflow/api",
        label: "BillingFlow API"
      },
      {
        to: "/billingflow/demo",
        label: "BillingFlow Demo"
      },
      {
        to: "/billingflow/changelog",
        label: "BillingFlow Changelog"
      },
      {
        to: "/agent",
        label: "AI Agent"
      },
      {
        to: "/agent/playground",
        label: "AI Agent Playground"
      },
      {
        to: "/agent/docs",
        label: "AI Agent Docs"
      },
      {
        to: "/agent/templates",
        label: "AI Agent Templates"
      },
      {
        to: "/agent/workflows",
        label: "AI Agent Workflows"
      },
      {
        to: "/agent/examples",
        label: "AI Agent Examples"
      },
      {
        to: "/pdf-automation",
        label: "PDF Automation"
      },
      {
        to: "/pdf-automation/docs",
        label: "PDF Docs"
      },
      {
        to: "/pdf-automation/demo",
        label: "PDF Demo"
      },
      {
        to: "/pdf-automation/templates",
        label: "PDF Templates"
      },
      {
        to: "/smart-home",
        label: "Smart Home Division"
      }
    ]
  },
  {
    title: "Trust & Support",
    links: [
      {
        to: "/security",
        label: "Security Center"
      },
      {
        to: "/status",
        label: "System Status"
      },
      {
        to: "/trust",
        label: "Trust Center"
      },
      {
        to: "/compliance",
        label: "Compliance Center"
      },
      {
        to: "/certifications",
        label: "Certifications"
      },
      {
        to: "/support",
        label: "Support Center"
      },
      {
        to: "/knowledge-base",
        label: "Knowledge Base"
      },
      {
        to: "/faq",
        label: "FAQ"
      },
      {
        to: "/testimonials",
        label: "Testimonials"
      }
    ]
  },
  {
    title: "Resources",
    links: [
      {
        to: "/blog",
        label: "Blog"
      },
      {
        to: "/case-studies",
        label: "Case Studies"
      },
      {
        to: "/whitepapers",
        label: "Whitepapers"
      },
      {
        to: "/press",
        label: "Press Releases"
      },
      {
        to: "/developers",
        label: "Developer Platform"
      },
      {
        to: "/playground",
        label: "AI Playground"
      },
      {
        to: "/architecture",
        label: "Technical Architecture"
      },
      {
        to: "/blog/what-is-hmorix-ai-solutions-guide",
        label: "What is HMorix? A Complete Guide to Our AI Solutions for Practical Business Adoption"
      },
      {
        to: "/blog/ai-business-automation-solutions",
        label: "Leveraging AI-Powered Automation for Efficient Business Operations"
      },
      {
        to: "/blog/billingflow-invoicing-simplification",
        label: "5 Ways HMorix's BillingFlow Simplifies Invoicing with AI-Driven Proactive Payment Strategies"
      }
    ]
  },
  {
    title: "Company",
    links: [
      {
        to: "/careers",
        label: "Careers"
      },
      {
        to: "/investors",
        label: "Investors"
      },
      {
        to: "/partners",
        label: "Partners"
      },
      {
        to: "/roadmap",
        label: "Roadmap"
      },
      {
        to: "/media-kit",
        label: "Media Kit"
      },
      {
        to: "/harsh-sharma",
        label: "Harsh Sharma"
      }
    ]
  },
  {
    title: "Service Areas",
    links: [
      {
        to: "/locations/hathras/web-app-development",
        label: "Hathras Web App Development"
      },
      {
        to: "/locations/hathras/hosting",
        label: "Hathras Hosting"
      },
      {
        to: "/locations/hathras/automation",
        label: "Hathras Automation"
      },
      {
        to: "/locations/hathras/ai-integration",
        label: "Hathras AI Integration"
      },
      {
        to: "/locations/hathras/software",
        label: "Hathras Software"
      },
      {
        to: "/locations/hathras/seo",
        label: "Hathras SEO"
      },
      {
        to: "/locations/hathras/products",
        label: "Hathras Products"
      },
      {
        to: "/locations/mathura/web-app-development",
        label: "Mathura Web App Development"
      },
      {
        to: "/locations/mathura/hosting",
        label: "Mathura Hosting"
      },
      {
        to: "/locations/mathura/automation",
        label: "Mathura Automation"
      },
      {
        to: "/locations/mathura/ai-integration",
        label: "Mathura AI Integration"
      },
      {
        to: "/locations/mathura/software",
        label: "Mathura Software"
      },
      {
        to: "/locations/mathura/seo",
        label: "Mathura SEO"
      },
      {
        to: "/locations/mathura/products",
        label: "Mathura Products"
      },
      {
        to: "/locations/aligarh/web-app-development",
        label: "Aligarh Web App Development"
      },
      {
        to: "/locations/aligarh/hosting",
        label: "Aligarh Hosting"
      },
      {
        to: "/locations/aligarh/automation",
        label: "Aligarh Automation"
      },
      {
        to: "/locations/aligarh/ai-integration",
        label: "Aligarh AI Integration"
      },
      {
        to: "/locations/aligarh/software",
        label: "Aligarh Software"
      },
      {
        to: "/locations/aligarh/seo",
        label: "Aligarh SEO"
      },
      {
        to: "/locations/aligarh/products",
        label: "Aligarh Products"
      },
      {
        to: "/locations/agra/web-app-development",
        label: "Agra Web App Development"
      },
      {
        to: "/locations/agra/hosting",
        label: "Agra Hosting"
      },
      {
        to: "/locations/agra/automation",
        label: "Agra Automation"
      },
      {
        to: "/locations/agra/ai-integration",
        label: "Agra AI Integration"
      },
      {
        to: "/locations/agra/software",
        label: "Agra Software"
      },
      {
        to: "/locations/agra/seo",
        label: "Agra SEO"
      },
      {
        to: "/locations/agra/products",
        label: "Agra Products"
      },
      {
        to: "/locations/vrindavan/web-app-development",
        label: "Vrindavan Web App Development"
      },
      {
        to: "/locations/vrindavan/hosting",
        label: "Vrindavan Hosting"
      },
      {
        to: "/locations/vrindavan/automation",
        label: "Vrindavan Automation"
      },
      {
        to: "/locations/vrindavan/ai-integration",
        label: "Vrindavan AI Integration"
      },
      {
        to: "/locations/vrindavan/software",
        label: "Vrindavan Software"
      },
      {
        to: "/locations/vrindavan/seo",
        label: "Vrindavan SEO"
      },
      {
        to: "/locations/vrindavan/products",
        label: "Vrindavan Products"
      },
      {
        to: "/locations/delhi/web-app-development",
        label: "Delhi Web App Development"
      },
      {
        to: "/locations/delhi/ai-integration",
        label: "Delhi AI Integration"
      },
      {
        to: "/locations/delhi/software",
        label: "Delhi Software"
      },
      {
        to: "/locations/delhi/seo",
        label: "Delhi SEO"
      },
      {
        to: "/locations/noida/web-app-development",
        label: "Noida Web App Development"
      },
      {
        to: "/locations/noida/ai-integration",
        label: "Noida AI Integration"
      },
      {
        to: "/locations/noida/software",
        label: "Noida Software"
      },
      {
        to: "/locations/noida/seo",
        label: "Noida SEO"
      },
      {
        to: "/locations/mumbai/web-app-development",
        label: "Mumbai Web App Development"
      },
      {
        to: "/locations/mumbai/ai-integration",
        label: "Mumbai AI Integration"
      },
      {
        to: "/locations/mumbai/software",
        label: "Mumbai Software"
      },
      {
        to: "/locations/mumbai/products",
        label: "Mumbai Products"
      },
      {
        to: "/locations/bengaluru/web-app-development",
        label: "Bengaluru Web App Development"
      },
      {
        to: "/locations/bengaluru/ai-integration",
        label: "Bengaluru AI Integration"
      },
      {
        to: "/locations/bengaluru/software",
        label: "Bengaluru Software"
      },
      {
        to: "/locations/bengaluru/products",
        label: "Bengaluru Products"
      }
    ]
  },
  {
    title: "Legal",
    links: [
      {
        to: "/terms",
        label: "Terms of Service"
      },
      {
        to: "/privacy",
        label: "Privacy Policy"
      }
    ]
  }
]
