package com.example.hmorix.model

enum class InvoiceStatus {
    DRAFT, SENT, PAID, OVERDUE
}

data class InvoiceItem(
    val id: String,
    val description: String,
    val quantity: Double,
    val unitPrice: Double
) {
    val total: Double get() = quantity * unitPrice
}

data class Invoice(
    val id: String,
    val invoiceNumber: String,
    val clientName: String,
    val clientEmail: String,
    val clientGstin: String,
    val clientAddress: String,
    val issueDate: String,
    val dueDate: String,
    val currency: String = "INR", // INR or USD
    val taxRate: Double = 18.0, // 18% GST standard
    val discount: Double = 0.0,
    val notes: String = "Payment via UPI, NEFT or Net Banking. Official invoice generated by HMorix BillingFlow.",
    val status: InvoiceStatus = InvoiceStatus.DRAFT,
    val items: List<InvoiceItem> = emptyList()
) {
    val subtotal: Double get() = items.sumOf { it.total }
    val discountAmount: Double get() = discount.coerceIn(0.0, subtotal)
    val taxableAmount: Double get() = (subtotal - discountAmount).coerceAtLeast(0.0)
    val taxAmount: Double get() = taxableAmount * (taxRate / 100.0)
    val totalDue: Double get() = taxableAmount + taxAmount
    val currencySymbol: String get() = if (currency == "INR") "₹" else "$"
}

data class User(
    val id: String,
    val email: String,
    val name: String,
    val role: String = "user",
    val company: String = "",
    val avatarUrl: String = "",
    val emailVerified: Boolean = true,
    val twoFactorEnabled: Boolean = false,
    val provider: String = "email"
)

data class AuthResult(
    val success: Boolean,
    val user: User? = null,
    val token: String? = null,
    val sessionCookie: String? = null,
    val error: String? = null,
    val require2fa: Boolean = false,
    val tempToken: String? = null
)

data class ProjectItem(
    val id: String,
    val name: String,
    val clientName: String,
    val clientEmail: String = "",
    val status: String = "in_progress", // planning, active, in_progress, completed
    val progress: Int = 0, // 0 to 100
    val budget: Double = 0.0,
    val currency: String = "INR",
    val deadline: String = "",
    val services: List<String> = emptyList(),
    val description: String = "",
    val assignedTeamName: String = "HMorix Core Engineering"
)

data class SupportTicket(
    val id: String,
    val number: String,
    val subject: String,
    val description: String,
    val priority: String = "medium", // low, medium, high, urgent
    val status: String = "open", // open, in_progress, resolved, closed
    val clientEmail: String = "",
    val clientName: String = "",
    val projectName: String = "",
    val createdAt: String = "Recently",
    val updatedAt: String = "Recently"
)

data class PricingPlan(
    val id: String,
    val name: String,
    val tag: String,
    val priceInr: String,
    val priceUsd: String,
    val billingPeriod: String,
    val description: String,
    val isPopular: Boolean = false,
    val features: List<String>
)

data class CaseMetric(
    val label: String,
    val value: String
)

data class CaseStudy(
    val slug: String,
    val title: String,
    val clientName: String,
    val industry: String,
    val location: String,
    val challenge: String,
    val solution: String,
    val excerpt: String,
    val metrics: List<CaseMetric>
)

data class EnterpriseService(
    val id: String,
    val title: String,
    val category: String,
    val description: String,
    val startingPrice: String,
    val highlights: List<String>
)

data class AgentExecutionStep(
    val title: String,
    val detail: String,
    val isCompleted: Boolean = false,
    val isRunning: Boolean = false
)

data class ChatMessage(
    val id: String,
    val sender: String, // "user", "assistant"
    val text: String,
    val timestamp: String = "Now"
)

data class ApiStatus(
    val endpoint: String,
    val status: String,
    val latencyMs: Long,
    val isHealthy: Boolean
)
