package com.example.hmorix.model

enum class InvoiceStatus {
    DRAFT, SENT, PAID, OVERDUE
}

data class InvoiceItem(
    val id: String,
    val description: String,
    val quantity: Double,
    val unitPrice: Double
) {
    val total: Double get() = quantity * unitPrice
}

data class Invoice(
    val id: String,
    val invoiceNumber: String,
    val clientName: String,
    val clientEmail: String,
    val clientGstin: String,
    val clientAddress: String,
    val issueDate: String,
    val dueDate: String,
    val currency: String = "INR", // INR or USD
    val taxRate: Double = 18.0, // 18% GST standard
    val discount: Double = 0.0,
    val notes: String = "Payment via UPI, NEFT or Net Banking. Official invoice generated by HMorix BillingFlow.",
    val status: InvoiceStatus = InvoiceStatus.DRAFT,
    val items: List<InvoiceItem> = emptyList()
) {
    val subtotal: Double get() = items.sumOf { it.total }
    val discountAmount: Double get() = discount.coerceIn(0.0, subtotal)
    val taxableAmount: Double get() = (subtotal - discountAmount).coerceAtLeast(0.0)
    val taxAmount: Double get() = taxableAmount * (taxRate / 100.0)
    val totalDue: Double get() = taxableAmount + taxAmount
    val currencySymbol: String get() = if (currency == "INR") "₹" else "$"
}

data class CaseMetric(
    val label: String,
    val value: String
)

data class CaseStudy(
    val slug: String,
    val title: String,
    val clientName: String,
    val industry: String,
    val location: String,
    val challenge: String,
    val solution: String,
    val excerpt: String,
    val metrics: List<CaseMetric>
)

data class EnterpriseService(
    val id: String,
    val title: String,
    val category: String,
    val description: String,
    val startingPrice: String,
    val highlights: List<String>
)

data class AgentExecutionStep(
    val title: String,
    val detail: String,
    val isCompleted: Boolean = false,
    val isRunning: Boolean = false
)

data class ChatMessage(
    val id: String,
    val sender: String, // "user", "assistant"
    val text: String,
    val timestamp: String = "Now"
)

data class ApiStatus(
    val endpoint: String,
    val status: String,
    val latencyMs: Long,
    val isHealthy: Boolean
)
