import re
import urllib.error
import urllib.request

from lib.google_search import search, is_configured, GoogleSearchError

TITLE_RE = re.compile(rb"<title[^>]*>(.*?)</title>", re.IGNORECASE | re.DOTALL)


def _fetch_title(url, timeout=8):
    """Best-effort <title> fetch for a user-supplied URL, purely for a nicer
    citation label. Never used to extract body content/claims — that would
    risk quoting copyrighted text; we only ever cite (title + link), and the
    writer paraphrases from the CSE snippet, not the raw page."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (whitepaper-researcher)"})
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            chunk = resp.read(65536)
        match = TITLE_RE.search(chunk)
        if match:
            return match.group(1).decode("utf-8", errors="replace").strip()
    except (urllib.error.URLError, TimeoutError, OSError, ValueError):
        pass
    return url


def research_topic(topic, source_urls=None, is_research=False, max_queries=3, results_per_query=5):
    """Returns {"sources": [...], "note": str}. Every entry is a REAL search
    result or a user-supplied URL — nothing here is generated by the LLM.
    The writer agent is told to only make a claim about a third party if it
    traces back to one of these sources.

    If GOOGLE_CSE isn't configured, this degrades gracefully: user-supplied
    source_urls are still included, and a note tells the writer (and later,
    the human reviewer) that no live research happened, so it must stick to
    the knowledge base + explicitly given key_facts and leave the rest as
    placeholders — same posture as the case-study writer without input data.
    """
    sources = []
    seen_urls = set()

    for url in (source_urls or []):
        url = (url or "").strip()
        if not url or url in seen_urls or url.startswith("["):
            continue
        seen_urls.add(url)
        sources.append({"title": _fetch_title(url), "url": url, "snippet": "(user-supplied source)"})

    note = None
    if not is_configured():
        note = ("GOOGLE_CSE_API_KEY / GOOGLE_CSE_CX not set — no live research was done. "
                "Only the knowledge base and explicitly supplied key_facts/source_urls were used; "
                "everything else stays a placeholder. See lib/google_search.py for the 5-minute setup.")
        return {"sources": sources, "note": note}

    queries = [topic]
    if is_research:
        queries.append(f"{topic} statistics 2026")
        queries.append(f"{topic} industry report")
    queries = queries[:max_queries]

    for q in queries:
        try:
            items = search(q, num=results_per_query)
        except GoogleSearchError as err:
            note = f"Research search failed partway ({err}); continuing with what was found so far."
            break
        for item in items:
            link = item.get("link")
            if not link or link in seen_urls:
                continue
            seen_urls.add(link)
            sources.append({
                "title": item.get("title", link),
                "url": link,
                "snippet": item.get("snippet", ""),
            })

    return {"sources": sources[:20], "note": note}
