# Converts a case-study JSON record (the same shape workflows/case_study_pipeline.py
# produces) into a standalone, statically-baked TSX page component. Same
# pattern as scripts/json_to_tsx.py for blog posts, extended with:
#   - a hero/poster image area (1200x630-ratio placeholder if no image yet)
#   - a client meta strip (industry / company size / timeline / service)
#   - a results grid (from the `results` array — placeholders render with a
#     visibly muted "placeholder" style so they're never mistaken for real
#     published numbers)
#   - a photo gallery grid
#   - a testimonial block (only rendered if hasTestimonial-equivalent data exists)
#   - a CTA section
#
# Usage (usually called by workflows/case_study_publish.py, not run directly):
#   python scripts/case_study_to_tsx.py path/to/case-study-record.json
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from lib.env import load_env  # noqa: E402

load_env()

OUTPUT_DIR = os.environ.get(
    "CASE_STUDY_PAGES_OUTPUT_DIR", os.path.join(os.getcwd(), "generated", "case-study-pages")
)
INDEX_FILE = os.environ.get(
    "CASE_STUDIES_INDEX_FILE", os.path.join(os.getcwd(), "generated", "caseStudiesIndex.json")
)
REGISTRY_FILE = os.path.join(OUTPUT_DIR, "registry.ts")

_TOKEN_SLUG = "__SLUG__"
_TOKEN_DATA_JSON = "__DATA_JSON__"
_TOKEN_COMPONENT_NAME = "__COMPONENT_NAME__"

COMPONENT_TEMPLATE = """// @ts-nocheck
// AUTO-GENERATED by scripts/case_study_to_tsx.py — do not edit by hand.
// Source slug: "__SLUG__". Regenerate by re-running the publish step.
import { Link } from 'react-router-dom'
import { Clock, ArrowLeft, Share2, Building2, MapPin, Layers, CalendarClock } from 'lucide-react'
import SEOHead from '../components/SEOHead'

const cs = __DATA_JSON__ as const

export default function __COMPONENT_NAME__() {
  const canonicalUrl = cs.canonicalUrl

  return (
    <>
      <SEOHead
        title={cs.seoTitle || cs.title}
        description={cs.metaDescription || cs.excerpt}
        canonicalUrl={canonicalUrl}
        openGraph={cs.openGraph}
        twitterCard={cs.twitterCard}
        jsonLd={cs.schemaJsonld}
      />

      <div className="pt-32 pb-20 min-h-screen">
        <div className="max-w-[900px] mx-auto px-8">
          <Link to="/case-studies" className="inline-flex items-center gap-2 text-sm text-cream/40 hover:text-[#C8FF00] mb-6 transition-colors">
            <ArrowLeft size={14} /> Back to Case Studies
          </Link>

          {cs.isDemo && (
            <div className="mb-6 px-4 py-2 bg-[#ffb454]/10 border border-[#ffb454]/30 rounded-[8px] text-xs text-[#ffb454] font-mono">
              DEMO / SAMPLE PROJECT — placeholder content, not a real published result.
            </div>
          )}

          <nav className="flex items-center gap-2 text-[11px] text-cream/30 font-mono mb-8 flex-wrap">
            {cs.breadcrumbs.map((b, i) => (
              <span key={i} className="flex items-center gap-2">
                {i > 0 && <span>/</span>}
                {i === cs.breadcrumbs.length - 1
                  ? <span className="text-cream/50">{b.name}</span>
                  : <Link to={b.url} className="hover:text-[#C8FF00]">{b.name}</Link>}
              </span>
            ))}
          </nav>

          <span className="inline-block px-2 py-0.5 bg-[#C8FF00]/10 text-[#C8FF00] text-xs font-mono rounded mb-4">{cs.category}</span>
          <h1 className="font-display text-3xl md:text-4xl font-bold mb-6">{cs.title}</h1>

          {/* Hero / poster image area — 1200x630 (OG-image ratio). Swap
              heroImageUrl for a real asset; until then this renders a
              clearly-labeled placeholder block instead of a broken <img>. */}
          <div className="relative w-full aspect-[1200/630] rounded-[12px] overflow-hidden border border-glass-border bg-obsidian-2 mb-10 flex items-center justify-center">
            {cs.heroImageUrl ? (
              <img src={cs.heroImageUrl} alt={cs.title} className="w-full h-full object-cover" />
            ) : (
              <div className="text-center px-6">
                <div className="text-cream/20 text-xs font-mono mb-2">POSTER / HERO IMAGE</div>
                <div className="text-cream/10 text-[10px] font-mono">1200 × 630 — add heroImageUrl to replace this placeholder</div>
              </div>
            )}
          </div>

          {/* Client meta strip */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10 pb-8 border-b border-glass-border">
            <div>
              <div className="flex items-center gap-1.5 text-cream/30 text-[10px] font-mono uppercase mb-1"><Building2 size={11} /> Client</div>
              <div className="text-sm text-cream/70">{cs.clientName}</div>
            </div>
            <div>
              <div className="flex items-center gap-1.5 text-cream/30 text-[10px] font-mono uppercase mb-1"><MapPin size={11} /> Industry</div>
              <div className="text-sm text-cream/70">{cs.industry}</div>
            </div>
            <div>
              <div className="flex items-center gap-1.5 text-cream/30 text-[10px] font-mono uppercase mb-1"><Layers size={11} /> Service</div>
              <div className="text-sm text-cream/70">{cs.serviceUsed}</div>
            </div>
            <div>
              <div className="flex items-center gap-1.5 text-cream/30 text-[10px] font-mono uppercase mb-1"><CalendarClock size={11} /> Timeline</div>
              <div className="text-sm text-cream/70">{cs.timeline}</div>
            </div>
          </div>

          <div className="flex items-center gap-6 mb-10 flex-wrap">
            <span className="flex items-center gap-1 text-xs text-cream/30"><Clock size={12} />{cs.readTime}</span>
            <span className="text-xs text-cream/30">{cs.publishedAt}</span>
            <button
              onClick={() => navigator.share ? navigator.share({ title: cs.title, url: canonicalUrl }) : navigator.clipboard.writeText(canonicalUrl)}
              className="ml-auto w-8 h-8 border border-glass-border rounded-[4px] flex items-center justify-center text-cream/40 hover:text-[#C8FF00] hover:border-[#C8FF00] transition-all"
            ><Share2 size={14} /></button>
          </div>

          {/* Results grid */}
          {cs.results && cs.results.length > 0 && (
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-12">
              {cs.results.map((r, i) => (
                <div key={i} className={`p-5 rounded-[10px] border ${r.isPlaceholder ? 'border-dashed border-cream/20 bg-transparent' : 'border-glass-border bg-obsidian-2'}`}>
                  <div className={`text-2xl font-display font-bold mb-1 ${r.isPlaceholder ? 'text-cream/20' : 'text-[#C8FF00]'}`}>{r.value}</div>
                  <div className="text-xs text-cream/40">{r.metric}</div>
                  {r.isPlaceholder && <div className="text-[10px] text-cream/20 font-mono mt-1">placeholder</div>}
                </div>
              ))}
            </div>
          )}

          <article className="prose prose-invert max-w-none">
            {cs.content.map((block, i) => {
              if (block.type === 'heading') {
                const HeadingTag = block.level === 3 ? 'h3' : 'h2'
                return <HeadingTag key={i} className="font-display text-xl font-bold mt-10 mb-4">{block.text}</HeadingTag>
              }
              if (block.type === 'list') {
                return (
                  <ul key={i} className="list-disc list-inside text-cream/60 leading-relaxed mb-4 space-y-1">
                    {(block.items || []).map((item, j) => <li key={j}>{item}</li>)}
                  </ul>
                )
              }
              if (block.type === 'table') {
                return (
                  <div key={i} className="overflow-x-auto my-6 border border-glass-border rounded-[8px]">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="bg-obsidian-2">
                          {(block.headers || []).map((h, j) => <th key={j} className="text-left px-4 py-2 text-cream/70 font-medium">{h}</th>)}
                        </tr>
                      </thead>
                      <tbody>
                        {(block.rows || []).map((row, r) => (
                          <tr key={r} className="border-t border-glass-border">
                            {row.map((cell, c) => <td key={c} className="px-4 py-2 text-cream/60">{cell}</td>)}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )
              }
              return <p key={i} className="text-cream/60 leading-relaxed mb-4 whitespace-pre-line">{block.text}</p>
            })}
          </article>

          {/* Photo gallery */}
          {cs.galleryImages && cs.galleryImages.length > 0 && (
            <div className="mt-14">
              <h3 className="font-display text-sm font-bold text-cream/70 mb-4">Project Gallery</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {cs.galleryImages.map((img, i) => (
                  <div key={i} className="aspect-square rounded-[8px] overflow-hidden border border-glass-border bg-obsidian-2 flex items-center justify-center">
                    {img.url ? (
                      <img src={img.url} alt={img.alt} className="w-full h-full object-cover" />
                    ) : (
                      <div className="text-center px-2">
                        <div className="text-cream/15 text-[9px] font-mono">{img.alt || 'PHOTO PLACEHOLDER'}</div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Testimonial */}
          {cs.hasTestimonial && cs.testimonialQuote && (
            <div className="mt-14 p-8 rounded-[12px] border border-glass-border bg-obsidian-2">
              <p className="text-lg font-display leading-relaxed text-cream/80 mb-4">"{cs.testimonialQuote}"</p>
              <div className="text-sm text-cream/50">{cs.testimonialAuthor}{cs.testimonialRole ? ` — ${cs.testimonialRole}` : ''}</div>
            </div>
          )}
          {!cs.hasTestimonial && (
            <div className="mt-14 p-8 rounded-[12px] border border-dashed border-cream/20 text-center">
              <p className="text-sm text-cream/25 font-mono">[Testimonial Placeholder — to be added once the client provides a quote]</p>
            </div>
          )}

          {/* Related links / backlinks / attachments */}
          {cs.referenceLinks && cs.referenceLinks.filter(l => l.url).length > 0 && (
            <div className="mt-14">
              <h3 className="font-display text-sm font-bold text-cream/70 mb-3">Related Links</h3>
              <ul className="space-y-2">
                {cs.referenceLinks.filter(l => l.url).map((l, i) => (
                  <li key={i}>
                    <a href={l.url} target="_blank" rel="noopener noreferrer" className="text-sm text-[#C8FF00] hover:underline">
                      {l.label || l.url}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* CTA */}
          <div className="mt-14 p-10 rounded-[16px] bg-[#C8FF00]/5 border border-[#C8FF00]/20 text-center">
            <h3 className="font-display text-xl font-bold mb-3">{cs.ctaText}</h3>
            <a href={cs.ctaUrl} className="inline-block mt-2 px-6 py-3 bg-[#C8FF00] text-[#0a0a0b] font-medium rounded-[8px] hover:opacity-90 transition-opacity">
              Get in touch
            </a>
          </div>
        </div>
      </div>
    </>
  )
}
"""


def slugify(text):
    text = (text or "").lower().strip()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-") or "case-study"


def component_name_for(slug):
    parts = re.split(r"[-_]+", slug)
    name = "".join(p.capitalize() for p in parts if p)
    return f"{name or 'CaseStudy'}Page"


def _to_camel(record):
    return {
        "title": record.get("title"),
        "slug": record.get("slug"),
        "excerpt": record.get("excerpt"),
        "category": record.get("category") or "Case Study",
        "content": record.get("content") or [],
        "readTime": record.get("read_time"),
        "publishedAt": record.get("published_at"),
        "isDemo": bool(record.get("is_demo", True)),
        "clientName": record.get("client_name"),
        "industry": record.get("industry"),
        "companySize": record.get("company_size"),
        "location": record.get("location"),
        "serviceUsed": record.get("service_used"),
        "timeline": record.get("timeline"),
        "results": record.get("results") or [],
        "hasTestimonial": bool(record.get("testimonial_quote")),
        "testimonialQuote": record.get("testimonial_quote"),
        "testimonialAuthor": record.get("testimonial_author"),
        "testimonialRole": record.get("testimonial_role"),
        "heroImageUrl": record.get("hero_image_url"),
        "galleryImages": record.get("gallery_images") or [],
        "ctaText": record.get("cta_text") or "Ready to build something like this?",
        "ctaUrl": record.get("cta_url") or "/contact",
        "referenceLinks": record.get("reference_links") or [],
        "seoTitle": record.get("seo_title"),
        "metaDescription": record.get("meta_description"),
        "canonicalUrl": record.get("canonical_url"),
        "openGraph": record.get("open_graph"),
        "twitterCard": record.get("twitter_card"),
        "breadcrumbs": record.get("breadcrumbs") or [],
        "schemaJsonld": record.get("schema_jsonld"),
        "wordCount": record.get("word_count"),
    }


def generate_case_study_page(record):
    slug = slugify(record.get("slug") or record.get("title"))
    component_name = component_name_for(slug)
    data_json = json.dumps(_to_camel(record), indent=2, ensure_ascii=False)

    tsx = (
        COMPONENT_TEMPLATE.replace(_TOKEN_SLUG, slug)
        .replace(_TOKEN_DATA_JSON, data_json)
        .replace(_TOKEN_COMPONENT_NAME, component_name)
    )

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    out_path = os.path.join(OUTPUT_DIR, f"{slug}.tsx")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(tsx)

    _update_registry()
    _update_index(record, slug)

    return slug, out_path


def _update_registry():
    if not os.path.isdir(OUTPUT_DIR):
        return
    slugs = sorted(
        f[:-4] for f in os.listdir(OUTPUT_DIR) if f.endswith(".tsx") and f != "registry.ts"
    )
    lines = [
        "// AUTO-GENERATED by scripts/case_study_to_tsx.py — do not edit by hand.",
        "// Maps slug -> lazily-loaded static case study page component.",
        "import { lazy } from 'react'",
        "",
        "export const caseStudyPageRegistry: Record<string, ReturnType<typeof lazy>> = {",
    ]
    for slug in slugs:
        lines.append(f"  '{slug}': lazy(() => import('./{slug}')),")
    lines.append("}")
    with open(REGISTRY_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def _update_index(record, slug):
    """Lightweight index for a /case-studies listing page + dashboard stats."""
    index = {}
    if os.path.exists(INDEX_FILE):
        try:
            with open(INDEX_FILE, "r", encoding="utf-8") as f:
                for item in json.load(f):
                    index[item["slug"]] = item
        except (json.JSONDecodeError, KeyError):
            index = {}

    index[slug] = {
        "slug": slug,
        "title": record.get("title"),
        "excerpt": record.get("excerpt"),
        "clientName": record.get("client_name"),
        "industry": record.get("industry"),
        "isDemo": bool(record.get("is_demo", True)),
        "canonicalUrl": record.get("canonical_url"),
        "publishedAt": record.get("published_at"),
        "wordCount": record.get("word_count"),
    }

    os.makedirs(os.path.dirname(INDEX_FILE), exist_ok=True)
    ordered = sorted(index.values(), key=lambda p: p.get("publishedAt") or "", reverse=True)
    with open(INDEX_FILE, "w", encoding="utf-8") as f:
        json.dump(ordered, f, indent=2, ensure_ascii=False)


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/case_study_to_tsx.py <path-to-record.json>")
        sys.exit(1)
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        record = json.load(f)
    slug, out_path = generate_case_study_page(record)
    from scripts.sync_frontend_content import sync_frontend_content

    sync_frontend_content()
    print(f"[case-study-to-tsx] Generated {out_path} (slug: {slug})")


if __name__ == "__main__":
    main()
