# Converts a blog post JSON record (the same shape daily_blog.py produces)
# into a standalone, statically-baked TSX page component — no runtime fetch,
# full SEO metadata (title/description/canonical/OG/Twitter/JSON-LD),
# breadcrumbs, and a "related articles" section from internal_links.
#
# Usage (usually called by workflows/publish.py, not run directly):
#   python scripts/json_to_tsx.py path/to/post-record.json
#
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

OUTPUT_DIR = os.environ.get(
    "BLOG_PAGES_OUTPUT_DIR", os.path.join(os.getcwd(), "generated", "blog-pages")
)
POSTS_INDEX_FILE = os.environ.get(
    "POSTS_INDEX_FILE", os.path.join(os.getcwd(), "generated", "postsIndex.json")
)
REGISTRY_FILE = os.path.join(OUTPUT_DIR, "registry.ts")

# Placeholder tokens instead of str.format()/f-strings for the big JSX
# template below — the template is full of literal `{` `}` for JSX
# expressions, and doubling every single one for .format() would be both
# unreadable and a single missed brace away from broken output.
_TOKEN_SLUG = "__SLUG__"
_TOKEN_DATA_JSON = "__DATA_JSON__"
_TOKEN_COMPONENT_NAME = "__COMPONENT_NAME__"

COMPONENT_TEMPLATE = """// @ts-nocheck
// AUTO-GENERATED by scripts/json_to_tsx.py — do not edit by hand.
// Source slug: "__SLUG__". Regenerate by re-running the publish step.
import { Link } from 'react-router-dom'
import { Clock, ArrowLeft, Share2, Bookmark, ThumbsUp } from 'lucide-react'
import SEOHead from '../components/SEOHead'

const post = __DATA_JSON__ as const

export default function __COMPONENT_NAME__() {
  const canonicalUrl = post.canonicalUrl

  return (
    <>
      <SEOHead
        title={post.seoTitle || post.title}
        description={post.metaDescription || post.excerpt}
        canonicalUrl={canonicalUrl}
        openGraph={post.openGraph}
        twitterCard={post.twitterCard}
        jsonLd={post.schemaJsonld}
      />
      <div className="pt-32 pb-20 min-h-screen">
        <div className="max-w-[800px] mx-auto px-8">
          <Link to="/blog" className="inline-flex items-center gap-2 text-sm text-cream/40 hover:text-[#C8FF00] mb-6 transition-colors">
            <ArrowLeft size={14} /> Back to Blog
          </Link>

          <nav className="flex items-center gap-2 text-[11px] text-cream/30 font-mono mb-8 flex-wrap">
            {post.breadcrumbs.map((b, i) => (
              <span key={i} className="flex items-center gap-2">
                {i > 0 && <span>/</span>}
                {i === post.breadcrumbs.length - 1
                  ? <span className="text-cream/50">{b.name}</span>
                  : <Link to={b.url} className="hover:text-[#C8FF00]">{b.name}</Link>}
              </span>
            ))}
          </nav>

          <span className="inline-block px-2 py-0.5 bg-[#C8FF00]/10 text-[#C8FF00] text-xs font-mono rounded mb-4">{post.category}</span>
          <h1 className="font-display text-3xl md:text-4xl font-bold mb-6">{post.title}</h1>

          <div className="flex items-center gap-6 mb-8 pb-8 border-b border-glass-border flex-wrap">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-obsidian-3 rounded-full flex items-center justify-center text-xs font-bold">
                {post.author.split(' ').map((n) => n[0]).join('')}
              </div>
              <div>
                <div className="text-sm font-medium">{post.author}</div>
                <div className="text-xs text-cream/30">{post.authorRole}</div>
              </div>
            </div>
            <span className="flex items-center gap-1 text-xs text-cream/30"><Clock size={12} />{post.readTime}</span>
            <span className="text-xs text-cream/30">{post.publishedAt}</span>
            {post.updatedAt && post.updatedAt !== post.publishedAt && (
              <span className="text-xs text-cream/30">Updated {post.updatedAt}</span>
            )}
            <div className="ml-auto flex items-center gap-2">
              <button
                onClick={() => navigator.share ? navigator.share({ title: post.title, url: canonicalUrl }) : navigator.clipboard.writeText(canonicalUrl)}
                className="w-8 h-8 border border-glass-border rounded-[4px] flex items-center justify-center text-cream/40 hover:text-[#C8FF00] hover:border-[#C8FF00] transition-all"
              ><Share2 size={14} /></button>
              <button className="w-8 h-8 border border-glass-border rounded-[4px] flex items-center justify-center text-cream/40 hover:text-[#C8FF00] hover:border-[#C8FF00] transition-all"><Bookmark size={14} /></button>
            </div>
          </div>

          <article className="prose prose-invert max-w-none">
            {post.content.map((block, i) => {
              if (block.type === 'heading') {
                const HeadingTag = block.level === 3 ? 'h3' : 'h2'
                return <HeadingTag key={i} className="font-display text-xl font-bold mt-10 mb-4">{block.text}</HeadingTag>
              }
              if (block.type === 'code') {
                return (
                  <pre key={i} className="bg-obsidian-2 border border-glass-border rounded-[8px] p-4 overflow-x-auto my-6">
                    <code className="text-xs text-cream/70 font-mono whitespace-pre">{block.text}</code>
                  </pre>
                )
              }
              if (block.type === 'list') {
                return (
                  <ul key={i} className="list-disc list-inside text-cream/60 leading-relaxed mb-4 space-y-1">
                    {(block.items || []).map((item, j) => <li key={j}>{item}</li>)}
                  </ul>
                )
              }
              if (block.type === 'table') {
                return (
                  <div key={i} className="overflow-x-auto my-6 border border-glass-border rounded-[8px]">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="bg-obsidian-2">
                          {(block.headers || []).map((h, j) => <th key={j} className="text-left px-4 py-2 text-cream/70 font-medium">{h}</th>)}
                        </tr>
                      </thead>
                      <tbody>
                        {(block.rows || []).map((row, r) => (
                          <tr key={r} className="border-t border-glass-border">
                            {row.map((cell, c) => <td key={c} className="px-4 py-2 text-cream/60">{cell}</td>)}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )
              }
              return <p key={i} className="text-cream/60 leading-relaxed mb-4 whitespace-pre-line">{block.text}</p>
            })}
          </article>

          {post.keywords.length > 0 && (
            <div className="mt-10 flex flex-wrap gap-2">
              {post.keywords.map((tag) => <span key={tag} className="px-2 py-0.5 bg-white/[0.06] text-cream/50 text-[10px] font-mono rounded">{tag}</span>)}
            </div>
          )}

          {post.internalLinks.length > 0 && (
            <div className="mt-10 pt-8 border-t border-glass-border">
              <h3 className="font-display text-sm font-bold text-cream/70 mb-4">Related articles</h3>
              <div className="flex flex-col gap-2">
                {post.internalLinks.map((link, i) => (
                  <Link key={i} to={`/blog/${link.slug}`} className="text-sm text-cream/50 hover:text-[#C8FF00] transition-colors">→ {link.title || link.text}</Link>
                ))}
              </div>
            </div>
          )}

          <div className="mt-12 pt-8 border-t border-glass-border flex items-center justify-between flex-wrap gap-4">
            <button className="flex items-center gap-2 px-4 py-2 bg-white/[0.04] border border-glass-border rounded-[8px] text-sm text-cream/50 hover:text-[#C8FF00] hover:border-[#C8FF00] transition-all">
              <ThumbsUp size={14} /> Helpful
            </button>
            <div className="flex items-center gap-2 text-xs text-cream/30">
              <span>Share:</span>
              <a href={`https://twitter.com/intent/tweet?url=${encodeURIComponent(canonicalUrl)}&text=${encodeURIComponent(post.title)}`} target="_blank" rel="noopener noreferrer" className="px-2 py-1 bg-white/[0.04] rounded hover:text-cream">Twitter</a>
              <a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(canonicalUrl)}`} target="_blank" rel="noopener noreferrer" className="px-2 py-1 bg-white/[0.04] rounded hover:text-cream">LinkedIn</a>
              <button onClick={() => navigator.clipboard.writeText(canonicalUrl)} className="px-2 py-1 bg-white/[0.04] rounded hover:text-cream">Copy Link</button>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
"""


def slugify(text):
    text = (text or "").lower().strip()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-") or "post"


def component_name_for(slug):
    parts = re.split(r"[-_]+", slug)
    name = "".join(p.capitalize() for p in parts if p)
    return f"{name or 'Post'}Page"


def _to_camel(record):
    """Maps the pipeline's snake_case record into the camelCase shape the
    generated component/TypeScript expects."""
    return {
        "title": record.get("title"),
        "slug": record.get("slug"),
        "excerpt": record.get("excerpt"),
        "category": record.get("category"),
        "content": record.get("content") or [],
        "readTime": record.get("read_time"),
        "author": record.get("author") or "HMorix AI",
        "authorRole": record.get("author_role") or "Editorial Team",
        "publishedAt": record.get("published_at"),
        "updatedAt": record.get("updated_at"),
        "seoTitle": record.get("seo_title"),
        "metaDescription": record.get("meta_description"),
        "canonicalUrl": record.get("canonical_url"),
        "openGraph": record.get("open_graph"),
        "twitterCard": record.get("twitter_card"),
        "breadcrumbs": record.get("breadcrumbs") or [],
        "schemaJsonld": record.get("schema_jsonld"),
        "keywords": record.get("keywords") or [],
        "internalLinks": record.get("internal_links") or [],
        "externalLinks": record.get("external_links") or [],
        "imagePrompts": record.get("image_prompts"),
    }


def generate_page(record):
    """Writes generated/blog-pages/<slug>.tsx for one post record. Returns
    the slug and file path written."""
    slug = slugify(record.get("slug") or record.get("title"))
    component_name = component_name_for(slug)
    data_json = json.dumps(_to_camel(record), indent=2, ensure_ascii=False)

    tsx = (
        COMPONENT_TEMPLATE.replace(_TOKEN_SLUG, slug)
        .replace(_TOKEN_DATA_JSON, data_json)
        .replace(_TOKEN_COMPONENT_NAME, component_name)
    )

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    out_path = os.path.join(OUTPUT_DIR, f"{slug}.tsx")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(tsx)

    _update_registry()
    _update_posts_index(record, slug)

    return slug, out_path


def _update_registry():
    """Rebuilds registry.ts from scratch by scanning every generated .tsx
    file — simpler and more robust than trying to append/edit an existing
    registry with regex."""
    if not os.path.isdir(OUTPUT_DIR):
        return
    slugs = sorted(
        f[:-4] for f in os.listdir(OUTPUT_DIR) if f.endswith(".tsx") and f != "registry.ts"
    )
    lines = [
        "// AUTO-GENERATED by scripts/json_to_tsx.py — do not edit by hand.",
        "// Maps slug -> lazily-loaded static page component.",
        "import { lazy } from 'react'",
        "",
        "export const blogPageRegistry: Record<string, ReturnType<typeof lazy>> = {",
    ]
    for slug in slugs:
        lines.append(f"  '{slug}': lazy(() => import('./{slug}')),")
    lines.append("}")
    with open(REGISTRY_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def _update_posts_index(record, slug):
    """Maintains a lightweight JSON index (title/excerpt/dates/etc, NOT full
    content) for the /blog listing page and for the sitemap/RSS generators
    to fall back on if Supabase is unreachable."""
    index = {}
    if os.path.exists(POSTS_INDEX_FILE):
        try:
            with open(POSTS_INDEX_FILE, "r", encoding="utf-8") as f:
                for item in json.load(f):
                    index[item["slug"]] = item
        except (json.JSONDecodeError, KeyError):
            index = {}

    index[slug] = {
        "slug": slug,
        "title": record.get("title"),
        "excerpt": record.get("excerpt"),
        "category": record.get("category"),
        "canonicalUrl": record.get("canonical_url"),
        "publishedAt": record.get("published_at"),
        "updatedAt": record.get("updated_at"),
    }

    os.makedirs(os.path.dirname(POSTS_INDEX_FILE), exist_ok=True)
    ordered = sorted(index.values(), key=lambda p: p.get("publishedAt") or "", reverse=True)
    with open(POSTS_INDEX_FILE, "w", encoding="utf-8") as f:
        json.dump(ordered, f, indent=2, ensure_ascii=False)


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/json_to_tsx.py <path-to-record.json>")
        sys.exit(1)
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        record = json.load(f)
    slug, out_path = generate_page(record)
    print(f"[json-to-tsx] Generated {out_path} (slug: {slug})")


if __name__ == "__main__":
    main()
