import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

OUTPUT_DIR = os.environ.get(
    "PRESS_PAGES_OUTPUT_DIR", os.path.join(os.getcwd(), "generated", "press-pages")
)
INDEX_FILE = os.environ.get(
    "PRESS_INDEX_FILE", os.path.join(os.getcwd(), "generated", "pressIndex.json")
)
REGISTRY_FILE = os.path.join(OUTPUT_DIR, "registry.ts")

COMPONENT_TEMPLATE = """// @ts-nocheck
// AUTO-GENERATED by scripts/press_to_tsx.py — do not edit by hand.
import { Link } from 'react-router-dom'
import { ArrowLeft, Download, Mail, Phone } from 'lucide-react'
import SEOHead from '../components/SEOHead'

const pr = __DATA_JSON__ as const

export default function __COMPONENT_NAME__() {
  return (
    <>
      <SEOHead
        title={pr.seoTitle || pr.headline}
        description={pr.metaDescription || pr.excerpt}
        canonicalUrl={pr.canonicalUrl}
        openGraph={pr.openGraph}
        twitterCard={pr.twitterCard}
        jsonLd={pr.schemaJsonld}
      />
      <div className="pt-32 pb-20 min-h-screen">
        <div className="max-w-[800px] mx-auto px-8">
          <Link to="/press" className="inline-flex items-center gap-2 text-sm text-cream/40 hover:text-[#C8FF00] mb-6 transition-colors">
            <ArrowLeft size={14} /> Back to Press
          </Link>
          <span className="inline-block px-2 py-0.5 bg-[#C8FF00]/10 text-[#C8FF00] text-xs font-mono rounded mb-4">{pr.category}</span>
          <div className="text-xs text-cream/40 font-mono mb-3">{pr.datelineCity} — {pr.datelineDate}</div>
          <h1 className="font-display text-3xl md:text-4xl font-bold mb-3">{pr.headline}</h1>
          {pr.subheadline && <p className="text-lg text-cream/50 mb-8">{pr.subheadline}</p>}

          {pr.coverImageUrl && (
            <div className="relative w-full aspect-[1200/630] rounded-[12px] overflow-hidden border border-glass-border bg-obsidian-2 mb-10">
              <img src={pr.coverImageUrl} alt={pr.headline} className="w-full h-full object-cover" />
            </div>
          )}

          <article className="prose prose-invert max-w-none">
            {pr.content.map((block, i) => {
              if (block.type === 'list') {
                return (
                  <ul key={i} className="list-disc list-inside text-cream/60 leading-relaxed mb-4 space-y-1">
                    {(block.items || []).map((item, j) => <li key={j}>{item}</li>)}
                  </ul>
                )
              }
              return <p key={i} className="text-cream/60 leading-relaxed mb-4 whitespace-pre-line">{block.text}</p>
            })}
          </article>

          {pr.hasQuote && pr.quoteText && (
            <div className="my-10 p-6 rounded-[12px] border-l-4 border-[#C8FF00] bg-obsidian-2">
              <p className="text-lg font-display leading-relaxed text-cream/80 mb-2">"{pr.quoteText}"</p>
              <div className="text-sm text-cream/50">{pr.quoteAttribution}{pr.quoteRole ? `, ${pr.quoteRole}` : ''}</div>
            </div>
          )}

          {pr.boilerplate && (
            <div className="mt-10 pt-8 border-t border-glass-border">
              <h3 className="font-display text-sm font-bold text-cream/70 mb-2">About HMorix</h3>
              <p className="text-sm text-cream/50 leading-relaxed">{pr.boilerplate}</p>
            </div>
          )}

          {(pr.mediaContactName || pr.mediaContactEmail) && (
            <div className="mt-8 p-5 rounded-[10px] border border-glass-border bg-obsidian-2">
              <div className="text-xs font-mono text-cream/30 uppercase mb-2">Media Contact</div>
              <div className="text-sm text-cream/70">{pr.mediaContactName}</div>
              {pr.mediaContactEmail && <div className="flex items-center gap-2 text-sm text-cream/50 mt-1"><Mail size={12} />{pr.mediaContactEmail}</div>}
              {pr.mediaContactPhone && <div className="flex items-center gap-2 text-sm text-cream/50 mt-1"><Phone size={12} />{pr.mediaContactPhone}</div>}
            </div>
          )}

          {pr.sources.length > 0 && (
            <div className="mt-10">
              <h3 className="font-display text-sm font-bold text-cream/70 mb-3">Sources</h3>
              <ol className="space-y-2 list-decimal list-inside">
                {pr.sources.map((s, i) => (
                  <li key={i} className="text-sm"><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-[#C8FF00] hover:underline">{s.title}</a></li>
                ))}
              </ol>
            </div>
          )}

          {pr.pdfUrl && (
            <a href={pr.pdfUrl} className="inline-flex items-center gap-2 mt-8 px-4 py-2 border border-glass-border rounded-[8px] text-sm text-cream/70 hover:border-[#C8FF00] hover:text-[#C8FF00] transition-colors">
              <Download size={14} /> Download PDF
            </a>
          )}

          <div className="mt-14 p-10 rounded-[16px] bg-[#C8FF00]/5 border border-[#C8FF00]/20 text-center">
            <h3 className="font-display text-xl font-bold mb-3">{pr.ctaText}</h3>
            <a href={pr.ctaUrl} className="inline-block mt-2 px-6 py-3 bg-[#C8FF00] text-[#0a0a0b] font-medium rounded-[8px] hover:opacity-90 transition-opacity">Get in touch</a>
          </div>
        </div>
      </div>
    </>
  )
}
"""


def slugify(text):
    text = (text or "").lower().strip()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-") or "press-release"


def component_name_for(slug):
    parts = re.split(r"[-_]+", slug)
    name = "".join(p.capitalize() for p in parts if p)
    return f"{name or 'PressRelease'}Page"


def _to_camel(record):
    return {
        "headline": record.get("headline"),
        "subheadline": record.get("subheadline"),
        "slug": record.get("slug"),
        "excerpt": record.get("excerpt"),
        "category": record.get("category") or "Company News",
        "datelineCity": record.get("dateline_city"),
        "datelineDate": record.get("dateline_date"),
        "content": record.get("content") or [],
        "hasQuote": bool(record.get("quote_text")),
        "quoteText": record.get("quote_text"),
        "quoteAttribution": record.get("quote_attribution"),
        "quoteRole": record.get("quote_role"),
        "boilerplate": record.get("boilerplate"),
        "mediaContactName": record.get("media_contact_name"),
        "mediaContactEmail": record.get("media_contact_email"),
        "mediaContactPhone": record.get("media_contact_phone"),
        "coverImageUrl": record.get("cover_image_url"),
        "sources": [{"title": s.get("title", s.get("url")), "url": s.get("url")} for s in (record.get("sources") or [])],
        "ctaText": record.get("cta_text") or "Learn more about HMorix",
        "ctaUrl": record.get("cta_url") or "/contact",
        "pdfUrl": record.get("pdf_url") or (f"/press-pdfs/{record.get('slug')}.pdf" if record.get("pdf_generated") else None),
        "seoTitle": record.get("seo_title"),
        "metaDescription": record.get("meta_description"),
        "canonicalUrl": record.get("canonical_url"),
        "openGraph": record.get("open_graph"),
        "twitterCard": record.get("twitter_card"),
        "breadcrumbs": record.get("breadcrumbs") or [],
        "schemaJsonld": record.get("schema_jsonld"),
    }


def generate_press_page(record):
    slug = slugify(record.get("slug") or record.get("headline"))
    component_name = component_name_for(slug)
    data_json = json.dumps(_to_camel(record), indent=2, ensure_ascii=False)

    tsx = COMPONENT_TEMPLATE.replace("__DATA_JSON__", data_json).replace("__COMPONENT_NAME__", component_name)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    out_path = os.path.join(OUTPUT_DIR, f"{slug}.tsx")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(tsx)

    _update_registry()
    _update_index(record, slug)
    return slug, out_path


def _update_registry():
    if not os.path.isdir(OUTPUT_DIR):
        return
    slugs = sorted(f[:-4] for f in os.listdir(OUTPUT_DIR) if f.endswith(".tsx") and f != "registry.ts")
    lines = [
        "// AUTO-GENERATED by scripts/press_to_tsx.py — do not edit by hand.",
        "import { lazy } from 'react'",
        "",
        "export const pressPageRegistry: Record<string, ReturnType<typeof lazy>> = {",
    ]
    for slug in slugs:
        lines.append(f"  '{slug}': lazy(() => import('./{slug}')),")
    lines.append("}")
    with open(REGISTRY_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def _update_index(record, slug):
    index = {}
    if os.path.exists(INDEX_FILE):
        try:
            with open(INDEX_FILE, "r", encoding="utf-8") as f:
                for item in json.load(f):
                    index[item["slug"]] = item
        except (json.JSONDecodeError, KeyError):
            index = {}
    index[slug] = {
        "slug": slug,
        "headline": record.get("headline"),
        "category": record.get("category"),
        "excerpt": record.get("excerpt"),
        "canonicalUrl": record.get("canonical_url"),
        "publishedAt": record.get("published_at"),
    }
    os.makedirs(os.path.dirname(INDEX_FILE), exist_ok=True)
    ordered = sorted(index.values(), key=lambda p: p.get("publishedAt") or "", reverse=True)
    with open(INDEX_FILE, "w", encoding="utf-8") as f:
        json.dump(ordered, f, indent=2, ensure_ascii=False)


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/press_to_tsx.py <path-to-record.json>")
        sys.exit(1)
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        record = json.load(f)
    slug, out_path = generate_press_page(record)
    print(f"[press-to-tsx] Generated {out_path} (slug: {slug})")


if __name__ == "__main__":
    main()
