import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from lib.env import load_env  # noqa: E402

load_env()

OUTPUT_DIR = os.environ.get(
    "WHITEPAPER_PAGES_OUTPUT_DIR", os.path.join(os.getcwd(), "generated", "whitepaper-pages")
)
INDEX_FILE = os.environ.get(
    "WHITEPAPERS_INDEX_FILE", os.path.join(os.getcwd(), "generated", "whitepapersIndex.json")
)
REGISTRY_FILE = os.path.join(OUTPUT_DIR, "registry.ts")

COMPONENT_TEMPLATE = """// @ts-nocheck
// AUTO-GENERATED by scripts/whitepaper_to_tsx.py — do not edit by hand.
import { Link } from 'react-router-dom'
import { Clock, ArrowLeft, Download, FileText } from 'lucide-react'
import SEOHead from '../components/SEOHead'

const wp = __DATA_JSON__ as const

export default function __COMPONENT_NAME__() {
  return (
    <>
      <SEOHead
        title={wp.seoTitle || wp.title}
        description={wp.metaDescription || wp.excerpt}
        canonicalUrl={wp.canonicalUrl}
        openGraph={wp.openGraph}
        twitterCard={wp.twitterCard}
        jsonLd={wp.schemaJsonld}
      />

      <div className="pt-32 pb-20 min-h-screen">
        <div className="max-w-[900px] mx-auto px-8">
          <Link to="/whitepapers" className="inline-flex items-center gap-2 text-sm text-cream/40 hover:text-[#C8FF00] mb-6 transition-colors">
            <ArrowLeft size={14} /> Back to White Papers
          </Link>

          <nav className="flex items-center gap-2 text-[11px] text-cream/30 font-mono mb-8 flex-wrap">
            {wp.breadcrumbs.map((b, i) => (
              <span key={i} className="flex items-center gap-2">
                {i > 0 && <span>/</span>}
                {i === wp.breadcrumbs.length - 1
                  ? <span className="text-cream/50">{b.name}</span>
                  : <Link to={b.url} className="hover:text-[#C8FF00]">{b.name}</Link>}
              </span>
            ))}
          </nav>

          <span className="inline-block px-2 py-0.5 bg-[#C8FF00]/10 text-[#C8FF00] text-xs font-mono rounded mb-4">White Paper</span>
          <h1 className="font-display text-3xl md:text-4xl font-bold mb-3">{wp.title}</h1>
          <p className="text-cream/50 mb-6">{wp.excerpt}</p>

          <div className="flex items-center gap-6 mb-8 flex-wrap">
            <span className="flex items-center gap-1 text-xs text-cream/30"><Clock size={12} />{wp.readTime}</span>
            <span className="text-xs text-cream/30">Topic: {wp.topic}</span>
            {wp.pdfUrl && (
              <a href={wp.pdfUrl} className="ml-auto inline-flex items-center gap-2 px-4 py-2 bg-[#C8FF00] text-[#0a0a0b] text-sm font-medium rounded-[8px] hover:opacity-90 transition-opacity">
                <Download size={14} /> Download PDF
              </a>
            )}
          </div>

          {wp.coverImageUrl && (
            <div className="relative w-full aspect-[1200/630] rounded-[12px] overflow-hidden border border-glass-border bg-obsidian-2 mb-10">
              <img src={wp.coverImageUrl} alt={wp.title} className="w-full h-full object-cover" />
            </div>
          )}

          {/* Table of contents */}
          {wp.tableOfContents.length > 0 && (
            <div className="mb-10 p-5 rounded-[10px] border border-glass-border bg-obsidian-2">
              <div className="text-xs font-mono text-cream/30 uppercase mb-2">Contents</div>
              <ul className="space-y-1">
                {wp.tableOfContents.map((t, i) => (
                  <li key={i} className="text-sm text-cream/60">{i + 1}. {t}</li>
                ))}
              </ul>
            </div>
          )}

          <article className="prose prose-invert max-w-none">
            {wp.content.map((block, i) => {
              if (block.type === 'heading') {
                const HeadingTag = block.level === 3 ? 'h3' : 'h2'
                return <HeadingTag key={i} className="font-display text-xl font-bold mt-10 mb-4">{block.text}</HeadingTag>
              }
              if (block.type === 'list') {
                return (
                  <ul key={i} className="list-disc list-inside text-cream/60 leading-relaxed mb-4 space-y-1">
                    {(block.items || []).map((item, j) => <li key={j}>{item}</li>)}
                  </ul>
                )
              }
              if (block.type === 'table') {
                return (
                  <div key={i} className="overflow-x-auto my-6 border border-glass-border rounded-[8px]">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="bg-obsidian-2">
                          {(block.headers || []).map((h, j) => <th key={j} className="text-left px-4 py-2 text-cream/70 font-medium">{h}</th>)}
                        </tr>
                      </thead>
                      <tbody>
                        {(block.rows || []).map((row, r) => (
                          <tr key={r} className="border-t border-glass-border">
                            {row.map((cell, c) => <td key={c} className="px-4 py-2 text-cream/60">{cell}</td>)}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )
              }
              return <p key={i} className="text-cream/60 leading-relaxed mb-4 whitespace-pre-line">{block.text}</p>
            })}
          </article>

          {/* Sources */}
          {wp.sources.length > 0 && (
            <div className="mt-14">
              <h3 className="font-display text-sm font-bold text-cream/70 mb-3 flex items-center gap-2"><FileText size={14} /> Sources</h3>
              <ol className="space-y-2 list-decimal list-inside">
                {wp.sources.map((s, i) => (
                  <li key={i} className="text-sm">
                    <a href={s.url} target="_blank" rel="noopener noreferrer" className="text-[#C8FF00] hover:underline">{s.title}</a>
                  </li>
                ))}
              </ol>
            </div>
          )}

          {/* Related white papers (backlinks) */}
          {wp.relatedWhitepapers.length > 0 && (
            <div className="mt-10">
              <h3 className="font-display text-sm font-bold text-cream/70 mb-3">Related White Papers</h3>
              <ul className="space-y-2">
                {wp.relatedWhitepapers.map((slug, i) => (
                  <li key={i}>
                    <Link to={`/whitepapers/${slug}`} className="text-sm text-[#C8FF00] hover:underline">{slug}</Link>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {wp.referenceLinks && wp.referenceLinks.filter(l => l.url).length > 0 && (
            <div className="mt-10">
              <h3 className="font-display text-sm font-bold text-cream/70 mb-3">Related Links</h3>
              <ul className="space-y-2">
                {wp.referenceLinks.filter(l => l.url).map((l, i) => (
                  <li key={i}>
                    <a href={l.url} target="_blank" rel="noopener noreferrer" className="text-sm text-[#C8FF00] hover:underline">{l.label || l.url}</a>
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div className="mt-14 p-10 rounded-[16px] bg-[#C8FF00]/5 border border-[#C8FF00]/20 text-center">
            <h3 className="font-display text-xl font-bold mb-3">{wp.ctaText}</h3>
            <a href={wp.ctaUrl} className="inline-block mt-2 px-6 py-3 bg-[#C8FF00] text-[#0a0a0b] font-medium rounded-[8px] hover:opacity-90 transition-opacity">
              Get in touch
            </a>
          </div>
        </div>
      </div>
    </>
  )
}
"""


def slugify(text):
    text = (text or "").lower().strip()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-") or "whitepaper"


def component_name_for(slug):
    parts = re.split(r"[-_]+", slug)
    name = "".join(p.capitalize() for p in parts if p)
    return f"{name or 'Whitepaper'}Page"


def _to_camel(record):
    section_titles = [
        b.get("text") for b in (record.get("content") or [])
        if b.get("type") == "heading" and b.get("level", 2) == 2
    ]
    return {
        "title": record.get("title"),
        "slug": record.get("slug"),
        "excerpt": record.get("excerpt"),
        "topic": record.get("topic"),
        "content": record.get("content") or [],
        "tableOfContents": section_titles,
        "readTime": record.get("read_time"),
        "coverImageUrl": record.get("cover_image_url"),
        "sources": [{"title": s.get("title", s.get("url")), "url": s.get("url")} for s in (record.get("sources") or [])],
        "relatedWhitepapers": record.get("related_whitepapers") or [],
        "referenceLinks": record.get("reference_links") or [],
        "ctaText": record.get("cta_text") or "Talk to HMorix about your project",
        "ctaUrl": record.get("cta_url") or "/contact",
        "pdfUrl": record.get("pdf_url") or (f"/whitepaper-pdfs/{record.get('slug')}.pdf" if record.get("pdf_generated") else None),
        "seoTitle": record.get("seo_title"),
        "metaDescription": record.get("meta_description"),
        "canonicalUrl": record.get("canonical_url"),
        "openGraph": record.get("open_graph"),
        "twitterCard": record.get("twitter_card"),
        "breadcrumbs": record.get("breadcrumbs") or [],
        "schemaJsonld": record.get("schema_jsonld"),
        "wordCount": record.get("word_count"),
    }


def generate_whitepaper_page(record):
    slug = slugify(record.get("slug") or record.get("title"))
    component_name = component_name_for(slug)
    data_json = json.dumps(_to_camel(record), indent=2, ensure_ascii=False)

    tsx = (
        COMPONENT_TEMPLATE.replace("__DATA_JSON__", data_json)
        .replace("__COMPONENT_NAME__", component_name)
    )

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    out_path = os.path.join(OUTPUT_DIR, f"{slug}.tsx")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(tsx)

    _update_registry()
    _update_index(record, slug)

    return slug, out_path


def _update_registry():
    if not os.path.isdir(OUTPUT_DIR):
        return
    slugs = sorted(f[:-4] for f in os.listdir(OUTPUT_DIR) if f.endswith(".tsx") and f != "registry.ts")
    lines = [
        "// AUTO-GENERATED by scripts/whitepaper_to_tsx.py — do not edit by hand.",
        "import { lazy } from 'react'",
        "",
        "export const whitepaperPageRegistry: Record<string, ReturnType<typeof lazy>> = {",
    ]
    for slug in slugs:
        lines.append(f"  '{slug}': lazy(() => import('./{slug}')),")
    lines.append("}")
    with open(REGISTRY_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def _update_index(record, slug):
    index = {}
    if os.path.exists(INDEX_FILE):
        try:
            with open(INDEX_FILE, "r", encoding="utf-8") as f:
                for item in json.load(f):
                    index[item["slug"]] = item
        except (json.JSONDecodeError, KeyError):
            index = {}

    index[slug] = {
        "slug": slug,
        "title": record.get("title"),
        "excerpt": record.get("excerpt"),
        "topic": record.get("topic"),
        "is_research": bool(record.get("is_research")),
        "canonicalUrl": record.get("canonical_url"),
        "publishedAt": record.get("published_at"),
        "wordCount": record.get("word_count"),
        "pdfGenerated": bool(record.get("pdf_generated")),
    }

    os.makedirs(os.path.dirname(INDEX_FILE), exist_ok=True)
    ordered = sorted(index.values(), key=lambda p: p.get("publishedAt") or "", reverse=True)
    with open(INDEX_FILE, "w", encoding="utf-8") as f:
        json.dump(ordered, f, indent=2, ensure_ascii=False)


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/whitepaper_to_tsx.py <path-to-record.json>")
        sys.exit(1)
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        record = json.load(f)
    slug, out_path = generate_whitepaper_page(record)
    from scripts.sync_frontend_content import sync_frontend_content

    sync_frontend_content()
    print(f"[whitepaper-to-tsx] Generated {out_path} (slug: {slug})")


if __name__ == "__main__":
    main()
